### ISSUE TITLE
[SceneFlow] [ERROR]  Error when adding prefab: ExtraAssetsImporter Water G87 Water Mirror 10 Brown Surface 

### ISSUE THREAD

**Issue by qualiall** [MiguelRita/RealVision-Decals#3]
I just started getting these errors-it seems for all of the Realvision set-I don't know if a mod updated, I have too many assets or what 

`[EXCEPTION]` - [10:50:58,211] - (Player.log)
[SceneFlow] [ERROR]  Error when adding prefab: ExtraAssetsImporter Water G87 Water Mirror 10 Brown Surface System.InvalidOperationException: system state is not initialized or has already been destroyed
	  at Unity.Entities.ComponentSystemBase.CheckedState () 
	  at Unity.Entities.ComponentSystemBase.get_EntityManager () 
	  at Game.Prefabs.PrefabSystem.AddPrefab (Game.Prefabs.PrefabBase prefab, System.String parentName, Game.Prefabs.PrefabBase parentPrefab, Game.Prefabs.ComponentBase parentComponent)``

**Comment by qualiall** [comment]
not sure if this is related or not, but I get this dialogue presented to me when I get to the main menu.  Hitting continue lets me progress
`[object Object]
NullReferenceException: Object reference not set to an instance of an object
  at Colossal.IO.AssetDatabase.PrefabAsset+PrefabReferenceResolver.TryResolveReference (System.String id, System.Object& value) [0x00052] in <710b80139fc14570aed29b63f9971b7b>:0 
  at Colossal.OdinSerializer.DeserializationContext.GetExternalObject (System.String id) [0x00033] in <5fbd906329d843a4a9e7066a41ace735>:0 
  at Colossal.OdinSerializer.AnySerializer.ReadValueWeak (Colossal.OdinSerializer.IDataReader reader) [0x006df] in <5fbd906329d843a4a9e7066a41ace735>:0 
  at Colossal.OdinSerializer.ReflectionFormatter`1[T].DeserializeImplementation (T& value, Colossal.OdinSerializer.IDataReader reader) [0x0013d] in <5fbd906329d843a4a9e7066a41ace735>:0 
Colossal.Logging.CustomLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Colossal.OdinSerializer.CustomLogger:LogException(Exception)
Colossal.OdinSerializer.DebugContext:LogException(Exception)
Colossal.OdinSerializer.ReflectionFormatter`1:DeserializeImplementation(ObjectMeshInfo&, IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Deserialize(IDataReader)
Colossal.OdinSerializer.ComplexTypeSerializer`1:ReadValue(IDataReader)
Colossal.OdinSerializer.ArrayFormatter`1:DeserializeImplementation(ObjectMeshInfo[]&, IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Deserialize(IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Colossal.OdinSerializer.IFormatter.Deserialize(IDataReader)
Colossal.OdinSerializer.AnySerializer:ReadValueWeak(IDataReader)
Colossal.OdinSerializer.ReflectionFormatter`1:DeserializeImplementation(StaticObjectPrefab&, IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Deserialize(IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Colossal.OdinSerializer.IFormatter.Deserialize(IDataReader)
Colossal.OdinSerializer.AnySerializer:ReadValueWeak(IDataReader)
Colossal.OdinSerializer.SerializationUtility:DeserializeValueWeak(IDataReader)
Colossal.OdinSerializer.SerializationUtility:DeserializeValueWeak(Stream, DataFormat, DeserializationContext)
Colossal.IO.AssetDatabase.PrefabAsset:Load()
Game.SceneFlow.GameManager:LoadPrefabs()
Game.SceneFlow.<Initialize>d__60:MoveNext()
System.Runtime.CompilerServices.MoveNextRunner:InvokeMoveNext(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Runtime.CompilerServices.MoveNextRunner:Run()
System.Threading.Tasks.<>c:<.cctor>b__7_0(Object)
UnityEngine.WorkRequest:Invoke()
UnityEngine.UnitySynchronizationContext:Exec()
UnityEngine.UnitySynchronizationContext:ExecuteTasks()`

**Comment by qualiall** [comment]
left off an important part of the story-they still work in game fine.

**Comment by MiguelRita** [comment]
It's hard to say for certain, but one thing is clear: the reported "Water G87 Water Mirror 10 Brown Surface" is not from the real vision pack. 
You could try rebuilding the "AssetsDataBase.json" file located in the "ExtraAssetsImporter" folder, as it may have become corrupted.
Hope this helps.
